[build]
builder = "NIXPACKS"
buildCommand = "npm run railway-build"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t ./build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
